name:          GH-Test
url:           http://yutopp.github.com/gh-test/

source:        .
destination:   ./_site
plugins:       ./_plugins

pamalink:      /:categories/:title.html

exclude:       ['__deploy', 'benri.rb', 'README.md']

# LangRefJP
llj_root:
  reference:
    
llj_api_ref:   /reference/api
