name:          DartRefJp
url:           http://dartrefjp.github.com
repository:    https://github.com/dartrefjp/dartrefjp.github.com/

source:        .
destination:   ./_site
plugins:       ./_plugins

pamalink:      /:categories/:title.html

exclude:       ['__deploy', '_dev_site', 'benri.rb', 'README.md']

# LangRefJP
llj_root:
  reference:
    
llj_api_ref:   /reference/api
